services:
  authservice.api:
    image: authservice.api
    build:
      context: .
      dockerfile: src/AuthService.Api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
